version: '3.9'
services:
  sqlsever:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqlserver
    environment:
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      "MSSQL_PID": "Express"
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql
volumes:
 mssql_data:

